name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install firebase
          npm install --save-dev gh-pages
          npm install @vitejs/plugin-react vite @types/react @types/react-dom
          npm install -D tailwindcss @tailwindcss/forms autoprefixer postcss

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist

deploy:
  needs: build
  steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: github-pages
        path: dist
    - uses: actions/deploy-pages@v4