name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # Install dependencies
      - name: Install dependencies
        run: |
          npm ci
          npm install firebase
          npm install --save-dev gh-pages
          npm install @vitejs/plugin-react vite @types/react @types/react-dom
          npm install -D tailwindcss @tailwindcss/forms autoprefixer postcss

      # Build the project
      - name: Build
        run: npm run build

      # Debug: List files in the `dist` folder
      - name: Verify dist folder
        run: ls -la ./dist

      # Upload the build output as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Download the artifact uploaded during the build step
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages

          # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3