name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      
      # Install all dependencies
      - name: Install Dependencies
        run: |
          rm -rf node_modules
          npm ci
          npm install
          npm install firebase peerjs react react-dom uuid
          npm install -D @vitejs/plugin-react vite @types/react @types/react-dom
          npm install -D gh-pages tailwindcss autoprefixer postcss
      
      # Configuration files (just to confirm)
      - name: Generate postcss.config.js
        run: echo "module.exports = { plugins: { tailwindcss: {}, autoprefixer: {} } };" > postcss.config.js

      - name: Generate tailwind.config.js
        run: |
          echo "module.exports = {" > tailwind.config.js
          echo "  content: [" >> tailwind.config.js
          echo "    './src/**/*.{js,jsx,ts,tsx}'," >> tailwind.config.js
          echo "    './index.html'," >> tailwind.config.js
          echo "  ]," >> tailwind.config.js
          echo "  theme: {" >> tailwind.config.js
          echo "    extend: {}," >> tailwind.config.js
          echo "  }," >> tailwind.config.js
          echo "  plugins: [" >> tailwind.config.js
          echo "    require('@tailwindcss/forms')({" >> tailwind.config.js
          echo "      strategy: 'class'," >> tailwind.config.js
          echo "    })," >> tailwind.config.js
          echo "  ]," >> tailwind.config.js
          echo "};" >> tailwind.config.js
      
      # Build the project
      - name: Build
        run: |
          npm run build
      
      # Debug: Check dist contents and size
      - name: Check dist
        run: |
          du -sh dist
          find dist -type f | wc -l
          ls -la dist

      # Upload for GitHub Pages
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4