name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install firebase
          npm install --save-dev gh-pages
          npm install @vitejs/plugin-react vite @types/react @types/react-dom --save-dev
          npm install -D tailwindcss @tailwindcss/forms autoprefixer postcss

      - name: Build
        run: |
          rm -rf dist
          npm run build
          ls -la ./dist

      - name: List files in dist folder
        run: ls -la ./dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages  # The name of the uploaded artifact
          path: './dist/public'  # Update this path if needed

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        with:
          branch: gh-pages  # Deploy to the gh-pages branch
          folder: dist  # The directory to deploy (Vite's default build output)
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: github-pages  # This should match the artifact name from the upload step
          preview: false
